server:
    port: 3001
db:
    url: 'mongodb://127.0.0.1:27017/'
    database: 'rocket'
    strategies: 'retryWrites=true&w=majority'

jwt:
    expiresIn: 3600
    secret: 'somesecret'

logging:
    values: 'log,error,warn,debug,verbose'